### ISSUE TITLE
Maybe a bug in last version (0.4.1)

### ISSUE THREAD

**Issue by mario6714** [Jeffchen54/KMPDownloader#1]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\m\Downloads\KMPDownloader-main\KMPDownloader.py", line 640, in <module>
    main()
  File "C:\Users\m\Downloads\KMPDownloader-main\KMPDownloader.py", line 632, in main
    downloader.routine(urls)
  File "C:\Users\m\Downloads\KMPDownloader-main\KMPDownloader.py", line 563, in routine
    self.__call_and_interpret_url(url)
  File "C:\Users\m\Downloads\KMPDownloader-main\KMPDownloader.py", line 504, in __call_and_interpret_url
    self.__process_window(url, True)
  File "C:\Users\m\Downloads\KMPDownloader-main\KMPDownloader.py", line 440, in __process_window
    reqs = requests.get(url)
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='kemono.party', port=443): Max retries exceeded with url: /fanbox/user/19627910(Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000019EB7F44DC0>, 'Connection to kemono.party timed out. (connect timeout=None)'))

**Comment by Jeffchen54** [comment]
Thanks for reaching out. Can you provide the URL you used? I'm having an issue pulling the URL up on my Chrome browser 'https://kemono.party/fanbox/user/19627910'. I think the issue is a bad URL was provided or something.

**Comment by mario6714** [comment]
https://kemono.party/patreon/user/19627910

**Comment by mario6714** [comment]
Sorry, my mistake in the first url, after that i cant enter using firefox or chrome

**Comment by Jeffchen54** [comment]
Interesting, are you using a txt file with the -f switch? Could you send me the invocation you used and any supporting text files?

**Comment by mario6714** [comment]
i use in this way in cmd:
KMPDownloader.py -v -d C:\Users\m\Downloads\KMPDownloader\
Input a url, or type 'quit' to exit> https://kemono.party/patreon/user/19627910

**Comment by mario6714** [comment]
supporting text files?

**Comment by Jeffchen54** [comment]
That's if you used a certain switch. If you used that invocation, there isn't any txt files. It seems to work on my end though. Could you try it again with the exact same invocation you sent me? You should not be getting

 requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='kemono.party', port=443): Max retries exceeded with url: /fanbox/user/19627910(Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000019EB7F44DC0>, 'Connection to kemono.party timed out. (connect timeout=None)'))

using that invocation since the program works by splitting URLs, it doesn't append anything to any URLs except if it is trying to download a file.

**Comment by mario6714** [comment]
Ty again this way?

i use in this way in cmd:
KMPDownloader.py -v -d C:\Users\m\Downloads\KMPDownloader
Input a url, or type 'quit' to exit> https://kemono.party/patreon/user/19627910

**Comment by Jeffchen54** [comment]
Yes

**Comment by mario6714** [comment]
Is fine if i use another url?

**Comment by Jeffchen54** [comment]
Yeah but make sure it is a valid URL, I believe you entered an incorrect one before. Let me know if it works.

**Comment by mario6714** [comment]
This URL https://kemono.party/fanbox/user/51803217

**Comment by Jeffchen54** [comment]
Yes that is valid, give a try and let me know if it goes through.

**Comment by mario6714** [comment]
Nop, for a moment the program download a few files but after that i get the same error:

Traceback (most recent call last):
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000002398A39A890>, 'Connection to kemono.party timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='kemono.party', port=443): Max retries exceeded with url: /fanbox/user/51803217/post/3760218 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002398A39A890>, 'Connection to kemono.party timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\m\Downloads\KMPDownloader-main\KMPDownloader.py", line 640, in <module>
    main()
  File "C:\Users\m\Downloads\KMPDownloader-main\KMPDownloader.py", line 632, in main
    downloader.routine(urls)
  File "C:\Users\m\Downloads\KMPDownloader-main\KMPDownloader.py", line 563, in routine
    self.__call_and_interpret_url(url)
  File "C:\Users\m\Downloads\KMPDownloader-main\KMPDownloader.py", line 504, in __call_and_interpret_url
    self.__process_window(url, True)
  File "C:\Users\m\Downloads\KMPDownloader-main\KMPDownloader.py", line 459, in __process_window
    self.__process_container(
  File "C:\Users\m\Downloads\KMPDownloader-main\KMPDownloader.py", line 348, in __process_container
    reqs = requests.get(url)
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\m\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='kemono.party', port=443): Max retries exceeded with url: /fanbox/user/51803217/post/3760218 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002398A39A890>, 'Connection to kemono.party timed out. (connect timeout=None)'))

**Comment by Jeffchen54** [comment]
I've managed to reproduced the error. The reason is because your computer disconnected from the Internet. I will implement a patch where connection attempts will be made continuously until a connection is made.

**Comment by mario6714** [comment]
After that error i can't enter kemono.party for a while but enter other url without error

**Comment by mario6714** [comment]
I have a error like this if i use the previous version:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1009, in _bootstrap_inner
  File "KMPDownloader.py", line 95, in run
  File "KMPDownloader.py", line 154, in download_file
  File "cfscrape\__init__.py", line 121, in request
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 667, in send
  File "requests\sessions.py", line 667, in <listcomp>
  File "requests\sessions.py", line 237, in resolve_redirects
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('Ð°Ð¿Ñ\x80Ð°Ð²Ð»ÐµÐ½Ñ\x8b Ð½Ð° Ð·Ð°Ð¿Ñ\x80Ð°Ñ\x88Ð¸Ð²Ð°ÐµÐ¼Ñ\x8bÐ¹ Ñ\x80ÐµÑ\x81Ñ\x83Ñ\x80Ñ\x81 Ð² Ð±Ð»Ð¸Ð¶Ð°Ð¹Ñ\x88ÐµÐµ Ð²Ñ\x80ÐµÐ¼Ñ\x8f.<br>Ð\x9fÐ¾Ð¶Ð°Ð»Ñ\x83Ð¹Ñ\x81Ñ\x82Ð° Ð¾Ð¶Ð¸Ð´Ð°Ð¹Ñ\x82Ðµ...",document.getElementById("link").innerHTML="Ð\x97Ð°Ñ\x89Ð¸Ñ\x82Ð° Ð¾Ñ\x82 DDoS-Ð°Ñ\x82Ð°Ðº DDoS-GUARD"):(document.getElementById("title").innerHTML="Checking your browser accessing "+host,document.getElementById("description").innerHTML="This process is automatic. Your browser will redirect to your requested content shortly.<br>Please allow up to 5 seconds...",document.getElementById("link").innerHTML="DDoS protection by DDoS-GUARD");</script></body></html>HTTP/1.1 403 Forbidden\r\n'))

**Comment by Jeffchen54** [comment]
Thanks for the info, I have finished the patch. It's past midnight for me but I got it working. Yeah the previous version 0.3.5 had some bugs I had taken care of. It definitely sounds like your ISP or network provider is having problems connecting to the Kemono.party website.

It contains the KMPDownloader.py, you can copy and paste it into where the old one is. It should solve the connection issues you had but it may hang out until your network provider reestablishes connection with the website. I haven't enough time to run my test cases since they take some time but it works when I intentionally break my connection with the website. Let me know if any more issues arise so I can fix them tomorrow.

[ConnectionPatch.zip](https://github.com/Jeffchen54/KMPDownloader/files/8885186/ConnectionPatch.zip)

**Comment by mario6714** [comment]
Sorry for bothering so late, here is 10:08 PM, thanks for the patch, i just need wait because in this moment i still cant connect to kemono.party.

**Comment by mario6714** [comment]
is working great now, thanks for the patch.

**Comment by Jeffchen54** [comment]
I have a more definitive patch coming later today that should counter most of the connection issues. It should work at least 25+ minutes when your computer loses connection to the server. I will release it after fine-tuning it and running my tests. Keep an eye on the releases!
